# Site settings
title: Cappui | We Craft Software Into Great Products.
email: daf@famoi.com
description: Cappui's is a startup studio crafting products into companies. Focusing on supply chains, internet-of-things (IoT), enterprise software and emerging technologies.
url: "https://cappui.com" # the base hostname & protocol for your site
twitter_username: CappuiLabs
port: 5000

# Build settings
markdown: kramdown
permalink: /:title

gems:
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-assets
  - sass
  - compass
  - uglifier

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Duncan Alistair Forbes
      layout: "post"
      category: progamming


assets:
  compress:
    css: sass
    js: uglifier

sass:
  sass_dir:          _assets
  style:            :compressed

